version: '3.9'
services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: bash -c "npm run build && npm start"
    volumes:
      - .:/app
